name: Automatically Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
      - name: Cache Next.js build
        uses: actions/cache@v2
        with:
          path: .next/cache
          key: ${{ runner.OS }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.[jt]s', '**/*.[jt]sx') }}
          restore-keys: ${{ runner.OS }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - name: Install dependencies
        run: npm install
      - name: Setup .env
        run: |
          echo MONGO_DB_URI=${{ secrets.MONGO_DB_URI }} >> .env.local
          echo GOOGLE_ID=${{ secrets.GOOGLE_ID }} >> .env.local
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env.local
          echo GOOGLE_SECRET=${{ secrets.GOOGLE_SECRET }} >> .env.local
          echo FACEBOOK_ID=${{ secrets.FACEBOOK_ID }} >> .env.local
          echo FACEBOOK_SECRET=${{ secrets.FACEBOOK_SECRET }} >> .env.local
          echo MY_APP_GITHUB_ID=${{ secrets.MY_APP_GITHUB_ID }} >> .env.local
          echo MY_APP_GITHUB_SECRET=${{ secrets.MY_APP_GITHUB_SECRET }} >> .env.local
          echo DOMAIN=${{ vars.DOMAIN }} >> .env.local
          echo NEXTAUTH_URL=${{ vars.NEXTAUTH_URL }} >> .env.local
      - name: Build Nextjs Application
        run: npm run build
