name: Automatically Deployment

on: 
  push:
    branches: 
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm install
      - name: Setup .env
        run: |
          echo MONGO_DB_URI=${{ secrets.MONGO_DB_URI }} >> .env.local
          echo GOOGLE_ID=${{ secrets.GOOGLE_ID }} >> .env.local
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env.local
          echo GOOGLE_SECRET=${{ secrets.GOOGLE_SECRET }} >> .env.local
      - name: Build Nextjs Application
        run: npm run build
